### ISSUE TITLE
Incorrect call of checkType in type construction

### ISSUE THREAD

**Issue by LiamGoodacre** [natefaubion/adt.js#12]
The call to `checkType` here: [adt.js#L66](https://github.com/natefaubion/adt.js/blame/master/adt.js#L66)

`checkType` expects a single type, not an array of them.  In the given context, this will always result in false.

I believe the correct usage is supposed to be:

``` js
        tmpl = checkType(Array, tmpl)
          ? adt.record.apply(null, tmpl)
          : adt.record(tmpl);
```

Looks like this occurred during this change: [Split out type checking function into two.](https://github.com/natefaubion/adt.js/commit/c13bd4c1ca51c84d0c28f5687a69d48ec069fc10#diff-3ca486cdcdb6c18ad55b17708929f0f5R65)

Fixing this allows one to define a cons-cell list as such:

``` js
> var adt = require('./adt')
> var List = adt.data('List')
> var Nil = List.type('Nil')
> var Cons = List.type('Cons', ['head', 'tail'])
> Cons(1, Nil)
{ head: 1, tail: {} }
```

Before the fix, the definition of `Cons` results in:

``` js
TypeError: Constraints must be functions
    at ctr.field (.../adt.js/adt.js:227:17)
    at Function.<anonymous> (.../adt.js/adt.js:181:44)
    at .../adt.js/adt.js:235:29
    at Function.D.type (.../adt.js/adt.js:76:15)
    at repl:1:17
    at REPLServer.defaultEval (repl.js:129:27)
    at REPLServer.b [as eval] (domain.js:251:18)
    at Interface.<anonymous> (repl.js:277:12)
    at Interface.EventEmitter.emit (events.js:103:17)
    at Interface._onLine (readline.js:194:10)
```

**Comment by natefaubion** [comment]
Definitely a bug.
