### ISSUE TITLE
Correct spelling of "seal".

### ISSUE THREAD

**Issue by ghost** [natefaubion/adt.js#3]
Hi... I think your API (or, at least, your documentation of it) should "seal" types rather than 'seeling' them!

**Comment by natefaubion** [comment]
hah, yeah. guess I should have googled more thoroughly. Just thought seal looked weird. All I could think of was the animal.

**Comment by ghost** [comment]
Nice work though. Did you know Zachary Kessin is writing a book on 'Javascript Monads'?

**Comment by natefaubion** [comment]
I remember reading something about that a while back, but haven't kept up with it.
