### ISSUE TITLE
constraints ran twice and more information for constraints

### ISSUE THREAD

**Issue by gregwebs** [natefaubion/adt.js#4]
It seems that create and set will end up calling apply, which will run the constraints again. I am only using create to make objects right now, so I made the changes below. Note that I am also passing vals and this to the constraints: this gives me more information, letting me do things like re-map fields in my schema definition. I think this needs to be changed to run in the constructor. The problem is that it is difficult to use the extra constraint information there as I am doing in create & set.

```
diff --git a/adt.js b/adt.js
index 30adb24..4552b4c 100644
--- a/adt.js
+++ b/adt.js
@@ -230,7 +230,7 @@
         if (args.length < len) throw new Error("Too few arguments");
         if (args.length > len) throw new Error("Too many arguments");
         for (var i = 0, len = args.length; i < len; i++) {
-          this[names[i]] = constraints[names[i]](args[i]);
+          this[names[i]] = args[i];
         }
       }
     };
@@ -277,7 +277,7 @@
       for (; i < len; i++) {
         n = names[i];
         val = n in vals ? vals[n] : this[n];
-        args.push(constraints[n](val));
+        args.push(constraints[n](val, vals, this));
       }
       return ctr.apply(null, args);
     };
@@ -308,7 +308,7 @@
       for (; i < len; i++) {
         n = names[i];
-         if (!(n in vals)) throw new Error("Too few arguments");
+        //if (!(n in vals)) throw new Error("Too few arguments");
-        args.push(constraints[n](vals[n]));
+        args.push(constraints[n](vals[n], vals, this));
       }
       return ctr.apply(null, args);
     };
```

**Comment by gregwebs** [comment]
What I am doing now is just adding a new method `fromApi` onto the record. I think it is better to not have the schema involved with re-naming.

**Comment by natefaubion** [comment]
I'm a little confused. Under what circumstances are constraints being called twice? Are you trying to call set from within a constraint?

I don't really like the idea of opening constraints to causing side effects on the record unless there is a really good use case. Maybe if you explain what you are doing in a little more detail?

**Comment by gregwebs** [comment]
sending a pull request
